version: '3.8'

services:
  api:
    build: .
    container_name: resume_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongoDB

  mongoDB:
    image: mongo:5.0
    restart: always
    container_name: mongoDB
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
